### ISSUE TITLE
java.lang.VerifyError exception for every method with @DebugLog in HTC phone

### ISSUE THREAD

**Issue by jolsondc** [JakeWharton/hugo#141]

**Comment by msgone** [comment]
I have the same Issue on a Samsung GT-I9301I with 4.4.2. 

> E/AndroidRuntime: FATAL EXCEPTION: main
>                                                               Process: ch.xxxxx.app, PID: 27848
>                                                               java.lang.VerifyError: de/xxxx/network/ErrorHandlingCallback$AjcClosure1
>                                                                   at de.xxxx.network.ErrorHandlingCallback.onUpdateUi(ErrorHandlingCallback.java:84)
>                                                                   at de.xxxx.network.ErrorHandlingCallback.onResponse(ErrorHandlingCallback.java:67)
>                                                                   at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
>                                                                   at android.os.Handler.handleCallback(Handler.java:733)
>                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                   at android.os.Looper.loop(Looper.java:136)
>                                                                   at android.app.ActivityThread.main(ActivityThread.java:5476)
>                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
>                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
>                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
>                                                                   at dalvik.system.NativeStart.main(Native Method)
