### ISSUE TITLE
java.lang.VerifyError while using @DebugLog anywhere in my app

### ISSUE THREAD

**Issue by MufriA** [JakeWharton/hugo#9]
```
        dalvikvm  W  VFY: invoke type does not match method type of Lcom/example/MyActivity;.someMethodToLog
                    W  VFY:  rejecting opcode 0x6f at 0x0000
                    W  VFY:  rejected Lcom/example/MyActivity;.access$1000 (Lcom/example/MyActivity;)V
                    W  Verifier rejected class Lcom/example/MyActivity;
                    W  Class init failed in newInstance call (Lcom/example/MyActivity;)
    AndroidRuntime  D  Shutting down VM
          dalvikvm  W  threadid=1: thread exiting with uncaught exception (group=0x417d3898)
    AndroidRuntime  E  FATAL EXCEPTION: main
                    E  java.lang.VerifyError: com/example/MyActivity
                    E      at java.lang.Class.newInstanceImpl(Native Method)
                    E      at java.lang.Class.newInstance(Class.java:1130)
                    E      at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
                    E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2220)
                    E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2359)
                    E      at android.app.ActivityThread.access$700(ActivityThread.java:165)
                    E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326)
                    E      at android.os.Handler.dispatchMessage(Handler.java:99)
                    E      at android.os.Looper.loop(Looper.java:137)
                    E      at android.app.ActivityThread.main(ActivityThread.java:5455)
                    E      at java.lang.reflect.Method.invokeNative(Native Method)
                    E      at java.lang.reflect.Method.invoke(Method.java:525)
                    E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
                    E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                    E      at dalvik.system.NativeStart.main(Native Method)
```

**Comment by msdx** [comment]
java.lang.VerifyError while using `@DebugLog` anywhere and `instant run` in my app.
hugo:1.1.0
com.android.tools.build:gradle:2.1.0

**Comment by reisub** [comment]
@msdx The latest Hugo version is 1.2.1, you should try with that one first as it should contain a fix for this issue.

**Comment by msdx** [comment]
@reisub The new version 1.2.1 has the same result.

```
java.lang.VerifyError: com/parkingwang/app/WangApplication$AjcClosure1
    at com.parkingwang.app.WangApplication.onCreate(WangApplication.java:92)
    at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:326)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4570)
    at android.app.ActivityThread.access$1300(ActivityThread.java:147)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5265)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:760)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by msdx** [comment]
https://code.google.com/p/android/issues/detail?id=202347&q=verifyerror&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened

**Comment by tentypwtk** [comment]
+1. latest hugo, gradle tools 2.0.0. Interestingly it only happens on older android I use for testing. No problems on 5.1, but old 4.1.2 phone crashes on any method annotated with @DebugLog.

**Comment by vboesch** [comment]
+1 same problem as tentypwtk, crash with device 4.4, but not newer android os version

**Comment by lovexiaov** [comment]
+1 same problem as tentypwtk, crash with device 4.4, but not newer android os version

**Comment by msdx** [comment]
+1 same problem as tentypwtk, crash with device 4.4, but not newer android os version

**Comment by epetrenko** [comment]
+1. I can confirm the appearance of this issue. Tested on Nexus 7 (2012 edition) with Android 4.2. Hugo version is the latest. Gradle version is 2.1.2. On newer android versions all is working just fine.

**Comment by asclines** [comment]
+1 Using Hugo version 1.2.1 and Gradle version 2.1.0

Works when minsdk = 20 but not when minsdk = 19
